namespace Subtitles.Domain.Entities;

/// <summary>
/// Current AI generation provenance — one row per (video, stage), upserted on regeneration.
/// This is what answers "which subtitles were generated by which prompt/model" — see
/// docs/Architecture.md §3.4 and docs/Database.md §2.11.
/// </summary>
public class AiGeneration
{
    public Guid Id { get; set; }

    public Guid VideoId { get; set; }
    public Video Video { get; set; } = null!;

    /// <summary>Set for NativeCleanup/TranslateToEnglish/Romanize (1:1 with a track); null otherwise.</summary>
    public Guid? SubtitleTrackId { get; set; }
    public SubtitleTrack? SubtitleTrack { get; set; }

    public GenerationStage Stage { get; set; }

    /// <summary>Populated only when Stage == Transcribe.</summary>
    public string? SpeechProvider { get; set; }
    public string? SpeechModel { get; set; }

    /// <summary>Populated for the four LLM stages.</summary>
    public string? LlmProvider { get; set; }
    public string? LlmModel { get; set; }

    public Guid? PromptVersionId { get; set; }
    public PromptVersion? PromptVersion { get; set; }

    /// <summary>Conventional values in <see cref="GenerationReasons"/>.</summary>
    public string Reason { get; set; } = null!;

    public DateTimeOffset GeneratedAt { get; set; }
}
