// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Subtitles.Infrastructure.Data;

#nullable disable

namespace Subtitles.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SubtitlesDbContext))]
    partial class SubtitlesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Subtitles.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PlanTier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("free")
                        .HasColumnName("plan_tier");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Subtitles.Domain.Entities.AiGeneration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("LlmModel")
                        .HasColumnType("text")
                        .HasColumnName("llm_model");

                    b.Property<string>("LlmProvider")
                        .HasColumnType("text")
                        .HasColumnName("llm_provider");

                    b.Property<Guid?>("PromptVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prompt_version_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("SpeechModel")
                        .HasColumnType("text")
                        .HasColumnName("speech_model");

                    b.Property<string>("SpeechProvider")
                        .HasColumnType("text")
                        .HasColumnName("speech_provider");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("stage");

                    b.Property<Guid?>("SubtitleTrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("subtitle_track_id");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.HasKey("Id")
                        .HasName("pk_ai_generations");

                    b.HasIndex("PromptVersionId")
                        .HasDatabaseName("ix_ai_generations_prompt_version_id");

                    b.HasIndex("SubtitleTrackId")
                        .HasDatabaseName("ix_ai_generations_subtitle_track_id");

                    b.HasIndex("Stage", "PromptVersionId")
                        .HasDatabaseName("ix_ai_generations_stage_prompt_version_id");

                    b.HasIndex("VideoId", "Stage")
                        .IsUnique()
                        .HasDatabaseName("ix_ai_generations_video_id_stage");

                    b.ToTable("ai_generations", (string)null);
                });

            modelBuilder.Entity("Subtitles.Domain.Entities.Export", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobPath")
                        .HasColumnType("text")
                        .HasColumnName("blob_path");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("format");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("SubtitleTrackType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("subtitle_track_type");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.HasKey("Id")
                        .HasName("pk_exports");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("ix_exports_video_id");

                    b.ToTable("exports", (string)null);
                });

            modelBuilder.Entity("Subtitles.Domain.Entities.ProcessingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("job_type");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<string>("LockedBy")
                        .HasColumnType("text")
                        .HasColumnName("locked_by");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.HasKey("Id")
                        .HasName("pk_processing_jobs");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("ix_processing_jobs_video_id");

                    b.HasIndex("Status", "AvailableAt", "CreatedAt")
                        .HasDatabaseName("ix_processing_jobs_status_available_at_created_at");

                    b.ToTable("processing_jobs", (string)null);
                });

            modelBuilder.Entity("Subtitles.Domain.Entities.PromptVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_active");

                    b.Property<string>("ModelParamsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("model_params_json");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("task");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_prompt_versions");

                    b.HasIndex("Task")
                        .IsUnique()
                        .HasDatabaseName("ix_prompt_versions_task")
                        .HasFilter("is_active");

                    b.HasIndex("Task", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_prompt_versions_task_version");

                    b.ToTable("prompt_versions", (string)null);
                });

            modelBuilder.Entity("Subtitles.Domain.Entities.SubtitleCue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EditedText")
                        .HasColumnType("text")
                        .HasColumnName("edited_text");

                    b.Property<int>("EndTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("end_time_ms");

                    b.Property<string>("GeneratedText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("generated_text");

                    b.Property<bool>("IsManuallyEdited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manually_edited");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<int>("StartTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("start_time_ms");

                    b.Property<Guid>("SubtitleTrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("subtitle_track_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_subtitle_cues");

                    b.HasIndex("SubtitleTrackId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_subtitle_cues_subtitle_track_id_sequence_number");

                    b.ToTable("subtitle_cues", (string)null);
                });

            modelBuilder.Entity("Subtitles.Domain.Entities.SubtitleTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("TrackType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("track_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.HasKey("Id")
                        .HasName("pk_subtitle_tracks");

                    b.HasIndex("VideoId", "TrackType")
                        .IsUnique()
                        .HasDatabaseName("ix_subtitle_tracks_video_id_track_type");

                    b.ToTable("subtitle_tracks", (string)null);
                });

            modelBuilder.Entity("Subtitles.Domain.Entities.Transcript", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_id");

                    b.Property<string>("WordTimestamps")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("word_timestamps");

                    b.HasKey("Id")
                        .HasName("pk_transcripts");

                    b.HasIndex("VideoId")
                        .IsUnique()
                        .HasDatabaseName("ix_transcripts_video_id");

                    b.ToTable("transcripts", (string)null);
                });

            modelBuilder.Entity("Subtitles.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_users_account_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Subtitles.Domain.Entities.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("AudioBlobPath")
                        .HasColumnType("text")
                        .HasColumnName("audio_blob_path");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("blob_path");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetectedLanguageCode")
                        .HasColumnType("text")
                        .HasColumnName("detected_language_code");

                    b.Property<decimal?>("DetectedLanguageConfidence")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("detected_language_confidence");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_file_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_videos");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_videos_account_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_videos_status");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_videos_uploaded_by_user_id");

                    b.ToTable("videos", (string)null);
                });

            modelBuilder.Entity("Subtitles.Domain.Entities.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CueId")
                        .HasColumnType("uuid")
                        .HasColumnName("cue_id");

                    b.Property<int?>("EndTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("end_time_ms");

                    b.Property<bool>("IsHighlightedAuto")
                        .HasColumnType("boolean")
                        .HasColumnName("is_highlighted_auto");

                    b.Property<bool?>("IsHighlightedManualOverride")
                        .HasColumnType("boolean")
                        .HasColumnName("is_highlighted_manual_override");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<int?>("StartTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("start_time_ms");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_words");

                    b.HasIndex("CueId", "SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_words_cue_id_sequence_number");

                    b.ToTable("words", (string)null);
                });

            modelBuilder.Entity("Subtitles.Domain.Entities.AiGeneration", b =>
                {
                    b.HasOne("Subtitles.Domain.Entities.PromptVersion", "PromptVersion")
                        .WithMany()
                        .HasForeignKey("PromptVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ai_generations_prompt_versions_prompt_version_id");

                    b.HasOne("Subtitles.Domain.Entities.SubtitleTrack", "SubtitleTrack")
                        .WithMany()
                        .HasForeignKey("SubtitleTrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ai_generations_subtitle_tracks_subtitle_track_id");

                    b.HasOne("Subtitles.Domain.Entities.Video", "Video")
                        .WithMany("AiGenerations")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ai_generations_videos_video_id");

                    b.Navigation("PromptVersion");

                    b.Navigation("SubtitleTrack");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Subtitles.Domain.Entities.Export", b =>
                {
                    b.HasOne("Subtitles.Domain.Entities.Video", "Video")
                        .WithMany("Exports")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exports_videos_video_id");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Subtitles.Domain.Entities.ProcessingJob", b =>
                {
                    b.HasOne("Subtitles.Domain.Entities.Video", "Video")
                        .WithMany("ProcessingJobs")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_processing_jobs_videos_video_id");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Subtitles.Domain.Entities.SubtitleCue", b =>
                {
                    b.HasOne("Subtitles.Domain.Entities.SubtitleTrack", "SubtitleTrack")
                        .WithMany("Cues")
                        .HasForeignKey("SubtitleTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subtitle_cues_subtitle_tracks_subtitle_track_id");

                    b.Navigation("SubtitleTrack");
                });

            modelBuilder.Entity("Subtitles.Domain.Entities.SubtitleTrack", b =>
                {
                    b.HasOne("Subtitles.Domain.Entities.Video", "Video")
                        .WithMany("SubtitleTracks")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subtitle_tracks_videos_video_id");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Subtitles.Domain.Entities.Transcript", b =>
                {
                    b.HasOne("Subtitles.Domain.Entities.Video", "Video")
                        .WithOne("Transcript")
                        .HasForeignKey("Subtitles.Domain.Entities.Transcript", "VideoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transcripts_videos_video_id");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Subtitles.Domain.Entities.User", b =>
                {
                    b.HasOne("Subtitles.Domain.Entities.Account", "Account")
                        .WithMany("Users")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Subtitles.Domain.Entities.Video", b =>
                {
                    b.HasOne("Subtitles.Domain.Entities.Account", "Account")
                        .WithMany("Videos")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_videos_accounts_account_id");

                    b.HasOne("Subtitles.Domain.Entities.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_videos_users_uploaded_by_user_id");

                    b.Navigation("Account");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("Subtitles.Domain.Entities.Word", b =>
                {
                    b.HasOne("Subtitles.Domain.Entities.SubtitleCue", "Cue")
                        .WithMany("Words")
                        .HasForeignKey("CueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_words_subtitle_cues_cue_id");

                    b.Navigation("Cue");
                });

            modelBuilder.Entity("Subtitles.Domain.Entities.Account", b =>
                {
                    b.Navigation("Users");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("Subtitles.Domain.Entities.SubtitleCue", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("Subtitles.Domain.Entities.SubtitleTrack", b =>
                {
                    b.Navigation("Cues");
                });

            modelBuilder.Entity("Subtitles.Domain.Entities.Video", b =>
                {
                    b.Navigation("AiGenerations");

                    b.Navigation("Exports");

                    b.Navigation("ProcessingJobs");

                    b.Navigation("SubtitleTracks");

                    b.Navigation("Transcript");
                });
#pragma warning restore 612, 618
        }
    }
}
